Exception in thread Thread-1 (send_bdpu_every_sec):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bogdan/Documents/INFORMATICA/Facultate/RL/teme/RL-Tema-1/switch.py", line 379, in send_bdpu_every_sec
    send_bdpu_to_link(trunk_port, root_bridge_id, sender_bridge_id, sender_path_cost)
  File "/home/bogdan/Documents/INFORMATICA/Facultate/RL/teme/RL-Tema-1/switch.py", line 363, in send_bdpu_to_link
    send_to_link(trunk_port.port_id, bpdu_data, int(bpdu_length))
  File "/home/bogdan/Documents/INFORMATICA/Facultate/RL/teme/RL-Tema-1/wrapper.py", line 60, in send_to_link
    assert(buffer_size < 1600)
TypeError: '<' not supported between instances of 'bytes' and 'int'
Traceback (most recent call last):
  File "/home/bogdan/Documents/INFORMATICA/Facultate/RL/teme/RL-Tema-1/switch.py", line 553, in <module>
    main()
  File "/home/bogdan/Documents/INFORMATICA/Facultate/RL/teme/RL-Tema-1/switch.py", line 533, in main
    on_receiving_bpdu(src_interface, data)
  File "/home/bogdan/Documents/INFORMATICA/Facultate/RL/teme/RL-Tema-1/switch.py", line 393, in on_receiving_bpdu
    bdpu_root_bridge_id: int = int(data[22:30])
ValueError: invalid literal for int() with base 10: b'\x00\x00\x00\x00\x00\x00\x00\x13'
